CREATE TABLE IF NOT EXISTS t_medication_plan (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    elderly_id BIGINT NOT NULL COMMENT '老人ID',
    drug_id BIGINT COMMENT '药品ID（已迁移到子表，保留冗余）',
    drug_name VARCHAR(100) COMMENT '药品名称（已迁移到子表，保留冗余）',
    dosage VARCHAR(50) COMMENT '用量（已迁移到子表，保留冗余）',
    dosage_unit VARCHAR(20) COMMENT '单位：mg/片/ml/粒（已迁移到子表，保留冗余）',
    frequency_type VARCHAR(20) COMMENT 'MULTI_DAILY/N_DAYS/PRN/ONCE',
    interval_days INT DEFAULT 1 COMMENT '间隔天数',
    time_slots VARCHAR(50) NOT NULL COMMENT '服药时段JSON: ["MORNING","EVENING"]',
    start_date DATE NOT NULL COMMENT '开始日期',
    end_date DATE COMMENT '结束日期（null=长期）',
    total_quantity DECIMAL(10,2) COMMENT '发药总量（已迁移到子表，保留冗余）',
    dosage_per_time VARCHAR(50) COMMENT '每次用量数值（已迁移到子表，保留冗余）',
    times_per_day INT DEFAULT 1 COMMENT '每天服用次数',
    depletion_date DATE COMMENT '预计耗尽日期（已迁移到子表，保留冗余）',
    instructions VARCHAR(500) COMMENT '服药说明',
    prescriber_name VARCHAR(50) COMMENT '处方医生',
    status VARCHAR(20) DEFAULT 'ACTIVE' COMMENT 'ACTIVE/PAUSED/COMPLETED/STOPPED',
    operator_id BIGINT,
    remark VARCHAR(200),
    org_id BIGINT,
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_elderly (elderly_id),
    INDEX idx_date_range (start_date, end_date),
    INDEX idx_status (status, deleted)
) COMMENT '老人用药计划';

CREATE TABLE IF NOT EXISTS t_medication_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    plan_id BIGINT COMMENT '关联用药计划ID',
    elderly_id BIGINT NOT NULL COMMENT '老人ID',
    drug_id BIGINT COMMENT '药品ID',
    drug_name VARCHAR(100) COMMENT '药品名称（冗余）',
    dosage VARCHAR(50) COMMENT '用量',
    record_date DATE COMMENT '服药日期',
    time_slot VARCHAR(20) COMMENT 'MORNING/AFTERNOON/EVENING/BEDTIME',
    status VARCHAR(20) DEFAULT 'PENDING' COMMENT 'PENDING/DONE/SKIPPED/MISSED/REFUSED',
    executor_id BIGINT COMMENT '执行护工ID',
    executor_name VARCHAR(50) COMMENT '执行护工姓名',
    executed_at DATETIME COMMENT '实际执行时间',
    skip_reason VARCHAR(200) COMMENT '跳过/漏服/拒服原因',
    remark VARCHAR(200),
    org_id BIGINT,
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_elderly_date (elderly_id, record_date),
    INDEX idx_date_slot (record_date, time_slot),
    INDEX idx_plan (plan_id)
) COMMENT '老人用药执行记录';

-- t_medication_plan_item: 用药计划药品明细（多药品子表）
CREATE TABLE IF NOT EXISTS t_medication_plan_item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    plan_id BIGINT NOT NULL COMMENT '关联用药计划ID',
    drug_id BIGINT NOT NULL COMMENT '药品ID',
    drug_name VARCHAR(100) NOT NULL COMMENT '药品名称（冗余）',
    dosage VARCHAR(50) COMMENT '用量说明，如饭后1片',
    dosage_unit VARCHAR(20) COMMENT '单位：mg/片/ml/粒',
    total_quantity DECIMAL(10,2) COMMENT '发药总量',
    dosage_per_time VARCHAR(50) COMMENT '每次用量数值',
    depletion_date DATE COMMENT '该药品预计耗尽日期',
    org_id BIGINT,
    deleted TINYINT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_plan (plan_id),
    INDEX idx_drug (drug_id)
) COMMENT '用药计划药品明细';
